###
POST http://localhost:5578/omnivore
Content-Type: application/json

{
  "action": "created",
  "userId": "ADD_OMNIVORE_USERID",
  "page": {
    "type": "page",
    "userId": "ADD_OMNIVORE_USERID",
    "id": "ADD_OMNIVORE_PAGEID",
    "slug": "fast-api-experiment-middleware-feature-by-life-is-short-so-enjoy-18a22a66735",
    "description": "While I worked on adding authentication into FastAPI application, I had a chance to take a look the FastAPI Middleware feature. Let’s try the example in FastAPI documentation. The example is adding…",
    "title": "FastAPI: Experiment Middleware feature | by Life-is-short--so--enjoy-it | Aug, 2023 | Medium",
    "author": "Life-is-short--so--enjoy-it",
    "originalUrl": "https://medium.com/@life-is-short-so-enjoy-it/fastapi-experiment-middleware-feature-c0a0c7314d74",
    "itemType": "ARTICLE",
    "textContentHash": "37e42d0dbd7b710094e77808a81bdd43",
    "thumbnail": "https://miro.medium.com/v2/resize:fit:1200/1*SDkMzvL5PNsIGchfG-N--w.png",
    "publishedAt": "2023-08-12T08:05:10.316Z",
    "readingProgressTopPercent": 0,
    "readingProgressHighestReadAnchor": 0,
    "state": "SUCCEEDED",
    "createdAt": "2023-08-23T13:47:25.365Z",
    "savedAt": "2023-08-23T13:47:25.365Z",
    "siteName": "Medium",
    "itemLanguage": "English",
    "siteIcon": "https://miro.medium.com/v2/1*m-R_BkNf1Qjr1YbyOIJY2w.png",
    "wordCount": 1257,
    "archivedAt": null
  }
}

### Get an omnivore article using it's slug id

GRAPHQL https://api-prod.omnivore.app/api/graphql
Cookie: auth=ADD_OMNIVORE_TOKEN

query Article {
       article(
           slug: "ADD_OMNIVORE_ARTICLE_ID"
           username: "."
           format: "markdown"
           ) {
             ... on ArticleSuccess {
               article {
                 title
                 content
                 labels {
                   name
                 }
               }
             }
           }
}

### Get latest 5 saved articles on omnivore

GRAPHQL https://api-prod.omnivore.app/api/graphql
Cookie: auth=ADD_OMNIVORE_TOKEN

query Search($after: String, $first: Int, $query: String) {
    search(first: $first, after: $after, query: $query) {
        ... on SearchSuccess {
            edges {
                cursor
                node {
                    id
                    title
                    slug
                    url
                    pageType
                    createdAt
                    isArchived
                    author
                    image
                    description
                    publishedAt
                    labels {
                        id
                        name
                        color
                    }
                    wordsCount
                }
            }
        }
        ... on SearchError {
            errorCodes
        }
    }
}

{
  "first": 5
}
